baseURL = "https://metaadvisor.eu/"
title = "MetaAdvisor.eu"
paginate = 24
paginatePath = "page"
enableRobotsTXT = true

# Glavni jezik = EN na rootu
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Permalinks: bez obzira gdje su fajlovi (2025/09/...),
# URL će uvijek biti /news/:filename/
[permalinks]
  news = "/news/:filename/"

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/news"
    languageCode = "en"

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de/news"
    languageCode = "de"

  [languages.hr]
    languageName = "Hrvatski"
    weight = 3
    contentDir = "content/hr/news"
    languageCode = "hr"

[params]
  tagline = "Automated summaries of news from publicly available sources."
  showAds = true

[taxonomies]
  tag = "tags"
  category = "categories"

# (za search i RSS)
[outputs]
  home = ["HTML", "RSS", "JSON"]
