baseURL = "/"
languageCode = "en"
title = "MetaAdvisor.eu"
paginate = 10
enableRobotsTXT = true

[params]
  tagline = "Automated summaries of news from publicly available sources."
  showAds = true

[taxonomies]
  tag = "tags"
  category = "categories"
