baseURL = "https://metaadvisor.eu/"
title = "MetaAdvisor.eu"
paginate = 24
paginatePath = "page"
enableRobotsTXT = true
ignoreFiles = ["^content/_inbox/"]  # (1) ne renderiraj _inbox

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[permalinks]
  news = "/news/:slug/"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"
    languageCode = "en"

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de"
    languageCode = "de"

  [languages.hr]
    languageName = "Hrvatski"
    weight = 3
    contentDir = "content/hr"
    languageCode = "hr"

[params]
tagline           = "Automated summaries of news from publicly available sources."
showAds           = true
placeholder_image = "/images/finance.jpg"

  [params.ads]
  provider = "a-ads"        # "a-ads" | "house"
  client   = "2411598"      # tvoj A-ADS Ad Unit ID
  slot     = ""             # ne koristi se za A-ADS

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]     # (2) omogući RSS na /news/ itd.
